### ISSUE TITLE
Why this error 

### ISSUE THREAD

**Issue by SiThuTuntimehacker** [fatihhcelik/XSSFinder#2]
python xssfinder.py
Traceback (most recent call last):
  File "xssfinder.py", line 3, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'

**Comment by fatihhcelik** [comment]
You should run autoinstall.sh file to install dependencies of  the XSSFinder(You can read readme for that). This error's means that you have to install termcolor library to be able ton run this program. Lastly, be sure you are using python3 over python2.
